// Services
export const RELOAD_SERVICE = 'RELOAD_SERVICE';
export const NAVIGATE_SERVICE_TO = 'NAVIGATE_SERVICE_TO';
export const OPEN_SERVICE_DEV_TOOLS = 'OPEN_SERVICE_DEV_TOOLS';
export const INITIALIZE_SERVICE_WEBVIEW = 'INITIALIZE_SERVICE_CONTEXT_MENU';
export const UPDATE_SPELLCHECKING_LANGUAGE = 'UPDATE_SPELLCHECKING_LANGUAGE';
export const REQUEST_SERVICE_SPELLCHECKING_LANGUAGE = 'REQUEST_SERVICE_SPELLCHECKING_LANGUAGE';
export const SERVICE_SPELLCHECKING_LANGUAGE = 'SERVICE_SPELLCHECKING_LANGUAGE';
export const RESIZE_SERVICE_VIEWS = 'RESIZE_SERVICE_VIEWS';
export const RESIZE_TODO_VIEW = 'RESIZE_TODO_VIEW';
export const HIDE_ALL_SERVICES = 'HIDE_ALL_SERVICES';
export const SHOW_ALL_SERVICES = 'SHOW_ALL_SERVICES';

// Overlay replacement for modals
export const OVERLAY_OPEN = 'OVERLAY_OPEN';
export const OVERLAY_SHARE_SETTINGS = 'OVERLAY_SHARE_SETTINGS';

// Share Franz Dialog
export const SHARE_FRANZ_GET_SERVICE_COUNT = 'SHARE_FRANZ_GET_SERVICE_COUNT';

// Plan Selection Dialog
export const PLAN_SELECTION_GET_DATA = 'PLAN_SELECTION_GET_DATA';
export const PLAN_SELECTION_TRIGGER_ACTION = 'PLAN_SELECTION_TRIGGER_ACTION';
