// Services
export const RELOAD_SERVICE = 'RELOAD_SERVICE';
export const NAVIGATE_SERVICE_TO = 'NAVIGATE_SERVICE_TO';
export const OPEN_SERVICE_DEV_TOOLS = 'OPEN_SERVICE_DEV_TOOLS';
export const INITIALIZE_SERVICE_WEBVIEW = 'INITIALIZE_SERVICE_CONTEXT_MENU';
export const UPDATE_SPELLCHECKING_LANGUAGE = 'UPDATE_SPELLCHECKING_LANGUAGE';
export const REQUEST_SERVICE_SPELLCHECKING_LANGUAGE = 'REQUEST_SERVICE_SPELLCHECKING_LANGUAGE';
export const SERVICE_SPELLCHECKING_LANGUAGE = 'SERVICE_SPELLCHECKING_LANGUAGE';
export const RESIZE_SERVICE_VIEWS = 'RESIZE_SERVICE_VIEWS';
export const RESIZE_TODO_VIEW = 'RESIZE_TODO_VIEW';
export const HIDE_ALL_SERVICES = 'HIDE_ALL_SERVICES';
export const SHOW_ALL_SERVICES = 'SHOW_ALL_SERVICES';
export const GET_ACTIVE_SERVICE_WEB_CONTENTS_ID = 'GET_ACTIVE_SERVICE_WEB_CONTENTS_ID';
export const ACTIVATE_SERVICE = 'ACTIVATE_SERVICE';
export const ACTIVATE_PREVIOUS_SERVICE = 'ACTIVATE_PREVIOUS_SERVICE';
export const ACTIVATE_NEXT_SERVICE = 'ACTIVATE_NEXT_SERVICE';
export const UPDATE_SERVICE_STATE = 'UPDATE_SERVICE_STATE';

// Overlay replacement for modals
export const OVERLAY_OPEN = 'OVERLAY_OPEN';
export const OVERLAY_SHARE_SETTINGS = 'OVERLAY_SHARE_SETTINGS';

// Share Franz Dialog
export const SHARE_FRANZ_GET_SERVICE_COUNT = 'SHARE_FRANZ_GET_SERVICE_COUNT';

// Plan Selection Dialog
export const PLAN_SELECTION_GET_DATA = 'PLAN_SELECTION_GET_DATA';
export const PLAN_SELECTION_TRIGGER_ACTION = 'PLAN_SELECTION_TRIGGER_ACTION';

// Todos
export const TODOS_FETCH_WEB_CONTENTS_ID = 'TODOS_FETCH_WEB_CONTENTS_ID';
export const TODOS_TOGGLE_DRAWER = 'TODOS_TOGGLE_DRAWER';
export const TODOS_TOGGLE_ENABLE_TODOS = 'TODOS_TOGGLE_ENABLE_TODOS';
export const TODOS_RELOAD = 'TODOS_RELOAD';
export const TODOS_OPEN_DEV_TOOLS = 'TODOS_OPEN_DEV_TOOLS';

// User
export const USER_LOGIN_STATUS = 'USER_LOGIN_STATUS';

// Settings
export const SETTINGS_NAVIGATE_TO = 'SETTINGS_NAVIGATE_TO';

// Workspaces
export const WORKSPACE_TOGGLE_DRAWER = 'WORKSPACE_TOGGLE_DRAWER';
export const WORKSPACE_OPEN_SETTINGS = 'WORKSPACE_OPEN_SETTINGS';
export const WORKSPACE_ACTIVATE = 'WORKSPACE_ACTIVATE';

// General
export const CHECK_FOR_UPDATE = 'CHECK_FOR_UPDATE';
export const FETCH_DEBUG_INFO = 'FETCH_DEBUG_INFO';
export const TOGGLE_FULL_SCREEN = 'TOGGLE_FULL_SCREEN';
export const CHECK_MACOS_PERMISSIONS = 'CHECK_MACOS_PERMISSIONS';
export const RELOAD_APP = 'RELOAD_APP';
