name: pats-franz
version: "5.0.0"
summary: Messaging app for various clients.
description: Messaging app for WhatsApp, Slack, Telegram, HipChat, Hangouts and many many more.

grade: stable
confinement: devmode

apps:
  pats-franz:
    command: desktop-launch $SNAP/opt/Franz/franz
    #desktop: usr/share/applications/franz.desktop
    plugs:
     - browser-support
     - network
     - unity7
     - gsettings

parts:
  pats-franz:
    plugin: dump
    source: ./out/franz_5.0.0-beta.15_amd64.deb
    source-type: deb
    after: [desktop-glib-only]
    stage-packages:
      - libappindicator1
      - libx11-dev
      - libxext-dev
      - libxss-dev
      - libxkbfile-dev
      - libgconf2-4
      - libnss3
